apiVersion: apps/v1
kind: Deployment
metadata:
  name: venudemonodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venudemonodejs
  template:
    metadata:
      labels:
        app: venudemonodejs
       
    spec:
      containers:
      - name: venudemonodejs
        image: mykubernetesregistryvenu.azurecr.io/project-2:v1
        ports:
        - name: web
          containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
      imagePullSecrets:
      - name: acr-secret
---
kind: Service
apiVersion: v1
metadata:
  name: venudemonodejs
  labels:
    app: venudemonodejs
spec:
  selector:
    app: venudemonodejs
  type: LoadBalancer    
  ports:
  - name: web
    port: 80
